apiVersion: v1
kind: Pod
metadata: 
  name: writer-three
spec:
  restartPolicy: Never
  containers:
   - image: gcr.io/google_containers/busybox
     command:
       - "/bin/sh"
       - "-c"
       - "while true; do echo $(hostname) $(date) >> /mnt/test/$(hostname); sleep 10; done"
     name: busybox
     volumeMounts:
       - name: myvol
         mountPath: /mnt/test
  volumes:
    - name: myvol
      persistentVolumeClaim:
        claimName: mypvc
        readOnly: false
  nodeSelector:
    kubernetes.io/hostname: shiftstack-tkbql-worker-0-h4f92
